import type { SnowflakeOptions, SnowflakeDeconstructed } from './constant.js';
declare class SnowflakeId {
    private static readonly NODE_ID_BITS;
    private static readonly SEQUENCE_BITS;
    private static readonly TIMESTAMP_BITS;
    private static readonly MAX_NODE_ID;
    private static readonly MAX_SEQUENCE;
    private static readonly MAX_TIMESTAMP;
    private static readonly NODE_ID_SHIFT;
    private static readonly TIMESTAMP_SHIFT;
    private static readonly DEFAULT_EPOCH;
    private readonly nodeId;
    private readonly epoch;
    private readonly clockSkewHandler;
    private readonly maxClockSkewWait;
    private sequence;
    private lastTimestamp;
    private clockBackwardsCount;
    private totalGenerated;
    private asyncQueue;
    private asyncLocked;
    constructor(options?: SnowflakeOptions);
    private resolveNodeId;
    private autoAssignNodeId;
    private simpleHash;
    private validateEpoch;
    next(cb?: (err: Error | null, id?: Buffer) => void): Buffer | undefined;
    nextId(): string;
    nextIdAsync(): Promise<string>;
    private doGenerateId;
    private doGenerateIdAsync;
    private handleClockBackwards;
    private handleClockBackwardsAsync;
    private waitNextMillisSync;
    private waitNextMillisAsync;
    private sleep;
    private acquireAsyncLock;
    private releaseAsyncLock;
    nextIds(count: number): string[];
    nextIdsAsync(count: number): Promise<string[]>;
    private doGenerateIds;
    private doGenerateIdsAsync;
    deconstruct(snowflakeId: string | Buffer | bigint): SnowflakeDeconstructed;
    validate(snowflakeId: string | Buffer | bigint): boolean;
    getStats(): {
        nodeId: number;
        epoch: number;
        lastTimestamp: number;
        sequence: number;
        maxSequence: number;
        maxNodeId: number;
        clockBackwardsCount: number;
        totalGenerated: number;
    };
    getNodeId(): number;
    getEpoch(): number;
    private generateId;
    private currentTimestamp;
    private bigintToBuffer;
    private bufferToBigint;
}
export default SnowflakeId;
//# sourceMappingURL=snowflake.d.ts.map