import { Snowflake, generateId, generateIdAsync, generateIds, generateIdsAsync, parseId, isValidId } from './index.js';
async function runTests() {
    console.log('=== 基本测试 ===');
    const id1 = generateId({ datacenter: 1, worker: 1 });
    const id2 = generateId({ datacenter: 1, worker: 1 });
    console.log('生成的ID1:', id1);
    console.log('生成的ID2:', id2);
    console.log('ID1 !== ID2:', id1 !== id2);
    console.log('ID长度:', id1.length);
    console.log('\n=== 批量生成测试 ===');
    const batchIds = generateIds(100, { datacenter: 2, worker: 3 });
    console.log('批量生成100个ID');
    console.log('所有ID唯一:', new Set(batchIds).size === batchIds.length);
    console.log('前5个ID:', batchIds.slice(0, 5));
    console.log('\n=== 异步生成测试 ===');
    const asyncId = await generateIdAsync({ id: 100 });
    console.log('异步生成的ID:', asyncId);
    const asyncIds = await generateIdsAsync(50, { id: 200 });
    console.log('异步批量生成50个ID，唯一性:', new Set(asyncIds).size === asyncIds.length);
    console.log('\n=== ID解析测试 ===');
    const parts = parseId(id1, { datacenter: 1, worker: 1 });
    console.log('ID1解析结果:', parts);
    console.log('时间戳验证:', new Date(parts.timestamp).toISOString());
    console.log('\n=== ID验证测试 ===');
    console.log('ID1有效性:', isValidId(id1, { datacenter: 1, worker: 1 }));
    console.log('无效ID测试:', isValidId('invalid-id'));
    console.log('空字符串测试:', isValidId(''));
    console.log('负数测试:', isValidId('-123'));
    console.log('\n=== 自动节点ID测试 ===');
    const autoId1 = generateId();
    const autoId2 = generateId();
    console.log('自动分配节点ID生成的ID1:', autoId1);
    console.log('自动分配节点ID生成的ID2:', autoId2);
    console.log('自动节点ID:', Snowflake.getNodeId());
    console.log('\n=== 时钟回拨策略测试 ===');
    const throwOptions = { id: 1, clockSkewHandler: 'throw' };
    console.log('使用 throw 策略的ID:', generateId(throwOptions));
    const adjustOptions = { id: 2, clockSkewHandler: 'auto_adjust' };
    console.log('使用 auto_adjust 策略的ID:', generateId(adjustOptions));
    console.log('\n=== 统计信息测试 ===');
    const stats = Snowflake.getStats({ datacenter: 1, worker: 1 });
    console.log('统计信息:', stats);
    console.log('\n=== 高并发测试 ===');
    const concurrentCount = 100;
    const promises = [];
    for (let i = 0; i < concurrentCount; i++) {
        promises.push(generateIdAsync({ id: 500 }));
    }
    const concurrentIds = await Promise.all(promises);
    console.log(`并发生成${concurrentCount}个ID`);
    console.log('所有ID唯一:', new Set(concurrentIds).size === concurrentIds.length);
    console.log('\n=== 性能测试 ===');
    const perfCount = 10000;
    const startTime = Date.now();
    const perfIds = generateIds(perfCount, { datacenter: 1, worker: 1 });
    const endTime = Date.now();
    console.log(`生成${perfCount}个ID耗时: ${endTime - startTime}ms`);
    console.log(`平均每个ID生成耗时: ${((endTime - startTime) / perfCount).toFixed(4)}ms`);
    console.log(`每秒可生成ID数量: ${Math.floor(perfCount / (endTime - startTime) * 1000)}`);
    console.log('\n=== Buffer格式测试 ===');
    const bufferId = Snowflake.generate({ id: 1 });
    console.log('Buffer格式ID:', bufferId);
    console.log('Buffer长度:', bufferId.length);
    const bufferParsed = parseId(bufferId, { id: 1 });
    console.log('Buffer解析结果:', bufferParsed);
    console.log('\n=== 所有测试完成 ===');
}
runTests().catch(console.error);
//# sourceMappingURL=test.js.map